export const IPC_CHANNELS = {
  PROJECT_SET_ACTIVE_PATH: 'project:setActivePath',
  PROJECT_GET_ACTIVE_PATH: 'project:getActivePath',
  PROJECT_LIST_KNOWN_PATHS: 'project:listKnownPaths',
  PROJECT_REMOVE_KNOWN_PATH: 'project:removeKnownPath',
  PROJECT_HEALTH: 'project:health',
  PROJECT_OPEN_DIALOG: 'project:openDialog',
  PROJECT_UPDATE_ADAPTER_CONFIG: 'project:updateAdapterConfig',
  PROJECT_GET_OVERRIDES: 'project:getOverrides',
  PROJECT_SET_OVERRIDES: 'project:setOverrides',
  PROCESSES_LIST: 'processes:list',
  EVENTS_BROADCAST: 'events:broadcast',
  EVENTS_RESET_STREAM: 'events:resetStream',
  QUEUES_STATS: 'queues:stats',
  QUEUES_FAILED: 'queues:failed',
  QUEUES_RETRY_JOB: 'queues:retryJob',
  QUEUES_FORGET_JOB: 'queues:forgetJob',
  QUEUES_PURGE_ALL: 'queues:purgeAll',
  LOGS_LIST_FILES: 'logs:listFiles',
  STREAM_PROCESS_LOG: 'stream:processLog',
  STREAM_APP_LOG: 'stream:appLog',
  STREAM_SUBSCRIBE: 'stream:subscribe',
  STREAM_UNSUBSCRIBE: 'stream:unsubscribe',
  UPDATER_UPDATE_AVAILABLE: 'updater:updateAvailable',
  UPDATER_OPEN_RELEASE: 'updater:openRelease',
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
